# Generated by Django 3.0.8 on 2020-07-20 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='seller',
        ),
    ]
